julia extract_alloc_cycle_split.jl -s 0 -e 10 -m configAll.ext &
julia extract_alloc_cycle_split.jl -s 10 -e 20 -m configAll.ext &
julia extract_alloc_cycle_split.jl -s 20 -e 30 -m configAll.ext &
julia extract_alloc_cycle_split.jl -s 30 -e 40 -m configAll.ext &
julia extract_alloc_cycle_split.jl -s 40 -e 50 -m configAll.ext &
julia extract_alloc_cycle_split.jl -s 50 -e 60 -m configAll.ext &
julia extract_alloc_cycle_split.jl -s 60 -e 70 -m configAll.ext &
julia extract_alloc_cycle_split.jl -s 70 -e 80 -m configAll.ext &
julia extract_alloc_cycle_split.jl -s 80 -e 90 -m configAll.ext &
julia extract_alloc_cycle_split.jl -s 90 -e 100 -m configAll.ext &
